#pragma once

#include <unordered_map>
#include <string>


//enum class NeuronSegment {
//	HipsPos = 0,
//	Hips = 1,
//	RightUpLeg = 2,
//	RightLeg = 3,
//	RightFoot = 4,
//	LeftUpLeg = 5,
//	LeftLeg = 6,
//	LeftFoot = 7,
//	Spine = 8,
//	Spine1 = 9,
//	Spine2 = 10,
//	Spine3 = 11,
//	Neck = 12,
//	Head = 13,
//	RightShoulder = 14,
//	RightArm = 15,
//	RightForeArm = 16,
//	RightHand = 17,
//	RightHandThumb1 = 18,
//	RightHandThumb2 = 19,
//	RightHandThumb3 = 20,
//	RightInHandIndex = 21,
//	RightHandIndex1 = 22,
//	RightHandIndex2 = 23,
//	RightHandIndex3 = 24,
//	RightInHandMiddle = 25,
//	RightHandMiddle1 = 26,
//	RightHandMiddle2 = 27,
//	RightHandMiddle3 = 28,
//	RightInHandRing	 = 29,
//	RightHandRing1	 = 30,
//	RightHandRing2	 = 31,
//	RightHandRing3	 = 32,
//	RightInHandPinky = 33,
//	RightHandPinky1	 = 34,
//	RightHandPinky2	 = 35,
//	RightHandPinky3	 = 36,
//	LeftShoulder	 = 37,
//	LeftArm			 = 38,
//	LeftForeArm		 = 39,
//	LeftHand		 = 40,
//	LeftHandThumb1	 = 41,
//	LeftHandThumb2	 = 42,
//	LeftHandThumb3	 = 43,
//	LeftInHandIndex	 = 44,
//	LeftHandIndex1	 = 45,
//	LeftHandIndex2	 = 46,
//	LeftHandIndex3	 = 47,
//	LeftInHandMiddle = 48,
//	LeftHandMiddle1	 = 49,
//	LeftHandMiddle2	 = 50,
//	LeftHandMiddle3	 = 51,
//	LeftInHandRing	 = 52,
//	LeftHandRing1	 = 53,
//	LeftHandRing2	 = 54,
//	LeftHandRing3	 = 55,
//	LeftInHandPinky	 = 56,
//	LeftHandPinky1	 = 57,
//	LeftHandPinky2	 = 58,
//	LeftHandPinky3	 = 59,
//	MAX = 60
//};


enum class NeuronSegment {
	Hips = 0,
	RightUpLeg = 1,
	RightLeg = 2,
	RightFoot = 3,
	LeftUpLeg = 4,
	LeftLeg = 5,
	LeftFoot = 6,
	Spine = 7,
	Spine1 = 8,
	Spine2 = 9,
	Spine3 = 10,
	Neck = 11,
	Head = 12,
	RightShoulder = 13,
	RightArm = 14,
	RightForeArm = 15,
	RightHand = 16,
	RightHandThumb1 = 17,
	RightHandThumb2 = 18,
	RightHandThumb3 = 19,
	RightInHandIndex = 20,
	RightHandIndex1 = 21,
	RightHandIndex2 = 22,
	RightHandIndex3 = 23,
	RightInHandMiddle = 24,
	RightHandMiddle1 = 25,
	RightHandMiddle2 = 26,
	RightHandMiddle3 = 27,
	RightInHandRing = 28,
	RightHandRing1 = 29,
	RightHandRing2 = 30,
	RightHandRing3 = 31,
	RightInHandPinky = 32,
	RightHandPinky1 = 33,
	RightHandPinky2 = 34,
	RightHandPinky3 = 35,
	LeftShoulder = 36,
	LeftArm = 37,
	LeftForeArm = 38,
	LeftHand = 39,
	LeftHandThumb1 = 40,
	LeftHandThumb2 = 41,
	LeftHandThumb3 = 42,
	LeftInHandIndex = 43,
	LeftHandIndex1 = 44,
	LeftHandIndex2 = 45,
	LeftHandIndex3 = 46,
	LeftInHandMiddle = 47,
	LeftHandMiddle1 = 48,
	LeftHandMiddle2 = 49,
	LeftHandMiddle3 = 50,
	LeftInHandRing = 51,
	LeftHandRing1 = 52,
	LeftHandRing2 = 53,
	LeftHandRing3 = 54,
	LeftInHandPinky = 55,
	LeftHandPinky1 = 56,
	LeftHandPinky2 = 57,
	LeftHandPinky3 = 58,
	MAX = 59
};

const std::unordered_map<NeuronSegment, std::string> NeuronSegmentName = {
	//{NeuronSegment::HipsPos, "HipsPos"},
	{NeuronSegment::Hips, "Hips"},
	{NeuronSegment::RightUpLeg, "RightUpLeg"},
	{NeuronSegment::RightLeg, "RightLeg"},
	{NeuronSegment::RightFoot, "RightFoot"},
	{NeuronSegment::LeftUpLeg, "LeftUpLeg"},
	{NeuronSegment::Neck, "Neck"},
	{NeuronSegment::Head, "Head"},
	{NeuronSegment::RightShoulder, "RightShoulder"},
	{NeuronSegment::LeftLeg, "LeftLeg"},
	{NeuronSegment::LeftFoot, "LeftFoot"},
	{NeuronSegment::Spine, "Spine"},
	{NeuronSegment::LeftShoulder, "LeftShoulder"},
	{NeuronSegment::Spine1, "Spine1"},
	{NeuronSegment::Spine2, "Spine2"},
	{NeuronSegment::LeftHand, "LeftHand"},
	{NeuronSegment::Spine3, "Spine3"},
	{NeuronSegment::Neck, "Neck"},
	{NeuronSegment::Head, "Head"},
	{NeuronSegment::RightShoulder, "RightToe"},
	{NeuronSegment::RightArm, "RightArm"},
	{NeuronSegment::RightForeArm, "RightForeArm"},
	{NeuronSegment::RightHand, "RightHand"},
	{NeuronSegment::RightHandThumb1, "RightHandThumb1"},
	{NeuronSegment::RightHand, "RightHand"},
	{NeuronSegment::RightHandThumb2, "RightHandThumb2"},
	{NeuronSegment::RightHandThumb3, "RightHandThumb3"},
	{NeuronSegment::RightInHandIndex, "RightInHandIndex"},
	{NeuronSegment::RightHandIndex1, "RightHandIndex1"},
	{NeuronSegment::RightHandIndex2, "RightHandIndex2"},
	{NeuronSegment::RightHandIndex3, "RightHandIndex3"},
	{NeuronSegment::RightInHandMiddle, "RightInHandMiddle"},
	{NeuronSegment::RightHandMiddle1, "RightHandMiddle1"},
	{NeuronSegment::RightHandMiddle2, "RightHandMiddle2"},
	{NeuronSegment::RightHandMiddle3, "RightHandMiddle3"},
	{NeuronSegment::RightInHandRing, "RightInHandRing"},
	{NeuronSegment::RightHandRing1, "RightHandRing1"},
	{NeuronSegment::RightHandRing2, "RightHandRing2"},
	{NeuronSegment::RightHandRing3, "RightHandRing3"},
	{NeuronSegment::RightInHandPinky, "RightInHandPinky"},
	{NeuronSegment::RightHandPinky1, "RightHandPinky1"},
	{NeuronSegment::RightHandPinky2, "RightHandPinky2"},
	{NeuronSegment::RightHandPinky3, "RightHandPinky3"},
	{NeuronSegment::LeftShoulder, "LeftShoulder"},
	{NeuronSegment::LeftArm, "LeftArm"},
	{NeuronSegment::LeftForeArm, "LeftForeArm"},
	{NeuronSegment::LeftHand, "LeftHand"},
	{NeuronSegment::LeftHandThumb1, "LeftHandThumb1"},
	{NeuronSegment::LeftHandThumb2, "LeftHandThumb2"},
	{NeuronSegment::LeftHandThumb3, "LeftHandThumb3"},
	{NeuronSegment::LeftInHandIndex, "LeftInHandIndex"},
	{NeuronSegment::LeftHandIndex1, "LeftHandIndex1"},
	{NeuronSegment::LeftHandIndex2, "LeftHandIndex2"},
	{NeuronSegment::LeftHandIndex3, "LeftHandIndex3"},
	{NeuronSegment::LeftInHandMiddle, "LeftInHandMiddle"},
	{NeuronSegment::LeftHandMiddle1, "LeftHandMiddle1"},
	{NeuronSegment::LeftHandMiddle2, "LeftHandMiddle2"},
	{NeuronSegment::LeftHandMiddle3, "LeftHandMiddle3"},
	{NeuronSegment::LeftInHandRing, "LeftInHandRing"},
	{NeuronSegment::LeftHandRing1, "LeftHandRing1"},
	{NeuronSegment::LeftHandRing2, "LeftHandRing2"},
	{NeuronSegment::LeftHandRing3, "LeftHandRing3"},
	{NeuronSegment::LeftInHandPinky, "LeftInHandPinky"},
	{NeuronSegment::LeftHandPinky1, "LeftHandPinky1"},
	{NeuronSegment::LeftHandPinky2, "LeftHandPinky2"},
	{NeuronSegment::LeftHandPinky2, "LeftHandPinky3"}
};